export * from './home/home';
export * from './profile/profile';
export * from './map/map';
export * from './loginRegister/loginRegister';
export * from './addPlace/addPlace';
export * from './addPlace/mapModal';
export * from './addPlace/addSchedule';
export * from './parameters/parameters';
export * from './map/addOccupant';